#%RAML 1.0
title: mod3-AmericanFlightSAPI
#baseUri: http://localhost:8081

types:
  AmericanFlight:
#flights is the main resource
/flights:
#get, post, put, patch, delete are methods(actions) acts upon the resource 
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
#we place sensitive info in the headers
    headers:
      client_id:
        required: false
      client_secret:
        required: false
#we can create fragment in 3 ways
    responses:
      200:
        body:
          application/json:
            examples:
              value: 
                -
                  ID: 1
                  code: Er38
                  price: 400
                  departureDate: 2023/10/17
                  origin: CLE
                  destination: SFO
                  emptySeats: 30
                  plane:
                    type: Boeing 333
                    totalSeats: 400           
  
                -
                  ID: 2
                  code: Er46
                  price: 600
                  departureDate: 2023/10/27
                  origin: CLE
                  destination: LAX
                  emptySeats: 20
                  plane:
                    type: Boeing 444
                    totalSeats: 600
                -
                  ID: 3
                  code: Er76
                  price: 700
                  departureDate: 2023/11/27
                  origin: CLE
                  destination: SFO
                  emptySeats: 60
                  plane:
                    type: Boeing 444
                    totalSeats:
  post:

# ID is nested resource
  /{ID}:
    get:
    delete:
    put:
    patch:
      
      