#%RAML 1.0
title: mod3-AmericanFlightSAPI
#baseUri: http://localhost:8081

types:
  AmericanFlight:
#flights is the main resource
/flights:
#get, post, put, patch, delete are methods(actions) acts upon the resource 
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
#we place sensitive info in the headers
    headers:
      client_id:
        required: false
      client_secret:
        required: false

    responses:
      200:
        body:
          application/json:
            examples:
              
              
  post:

# ID is nested resource
  /{ID}:
    get:
    delete:
    put:
    patch:
      
      