#%RAML 1.0
title: mod3-AmericanFlightSAPI

types:
  AmericanFlight:

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
  
  post:
    
  /{ID}: