#%RAML 1.0 DataType
type: object
properties:
    ID: number
    code:string
    price: 400
    departureDate: 2023/10/17
    origin: CLE
    destination: SFO
    emptySeats: 30
    plane:
      type: Boeing 333
      totalSeats: 400 
  





          

  
    ID: 2
    code: Er46
    price: 600
    departureDate: 2023/10/27
    origin: CLE
    destination: LAX
    emptySeats: 20
    plane:
      type: Boeing 444
      totalSeats: 600
  -
    ID: 3
    code: Er76
    price: 700
    departureDate: 2023/11/27
    origin: CLE
    destination: SFO
    emptySeats: 60
    plane:
      type: Boeing 555
      totalSeats: 350

